server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb:http://USER-SERVICE
          predicates:
          - Path=/api/v1/users/**
        - id: post-service
          uri: lb:http://POST-SERVICE
          predicates:
          - Path=/api/v1/posts/**