CREATE TABLE IF NOT EXISTS posts
(
	id SERIAL PRIMARY KEY,
	content VARCHAR(300) NOT NULL,
	user_id BIGINT NOT NULL,
	num_of_likes INTEGER NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);